### ISSUE TITLE
Document Embedded Domain Allowlist

### ISSUE THREAD

**Issue by bryan-at-looker** [looker-open-source/micro-admin-for-looker#3]
Looker 7.14+
Looker OAuth tokens require the domain to be whitelisted within the [Embedded Domain Allowlist](https://docs.looker.com/admin-options/platform/embed#embedded_domain_allowlist)

The place where the Domain Allowlist for OAuth API tokens for Looker is subject to change in the future, but is a necessary call-out for setting up micro-admin for the first time on a Looker instance.

**Comment by fabio-looker** [comment]
Thanks! Doc'd in https://github.com/looker-open-source/micro-admin-for-looker/commit/4c89706dc80d21d72c31ad026d5766ee4a3838a6
