### ISSUE TITLE
TypeError when checking corsApiResponse headers

### ISSUE THREAD

**Issue by tpakeman** [looker-open-source/micro-admin-for-looker#4]
* Node is version `v16.13.2`
* micro-admin is version `0.1.0` installed today (2022-02-03)
* Looker is newly installed `v22.0`
* micro admin works fine if the problematic line below is commented out

---

Running `node index.js` in the `/server` directory yields the following error: 

```
{"f":"(Internal) setup-host","h":"sandbox.looker.tompakeman.net","t":"API Call","call":"GET user","msec":212,"code":200,"resId":1}
TypeError: Cannot read properties of undefined (reading 'access-control-allow-origin')
    at setupHost (/Users/tompakeman/Documents/code/looker/looker-mu-admin-demo/server/lib/setup-host.js:112:66)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/tompakeman/Documents/code/looker/looker-mu-admin-demo/server/index.js:37:3
    at async Promise.all (index 0)
    at async main (/Users/tompakeman/Documents/code/looker/looker-mu-admin-demo/server/index.js:39:2)
```
---
The relevant code is `/server/lib/setup-host.js` line 112:
`const corsIsAllowed = corsApiResponse && corsApiResponse.headers['access-control-allow-origin'] == origin`

This is because `corsApiResponse.headers` is undefined for me. Logging `Object.keys(corsApiResponse)` only yields the following:
```
[
  '_readableState',   '_events',
  '_eventsCount',     '_maxListeners',
  'socket',           'httpVersionMajor',
  'httpVersionMinor', 'httpVersion',
  'complete',         'rawHeaders',
  'rawTrailers',      'aborted',
  'upgrade',          'url',
  'method',           'statusCode',
  'statusMessage',    'client',
  '_consuming',       '_dumped',
  'req',              'body'
]
```

**Comment by fabio-looker** [comment]
This is fixed by https://github.com/looker-open-source/micro-admin-for-looker/commit/7a5d31278acc9dd3129585d41ddeb87966d8c1cb
